language: c

sudo: required
dist: xenial

# Build only master, tags and PR's
# This prevents double builds on PRs (PR + branch build).
# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-441393807
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

compiler: 
  - gcc

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

script:
  - LOG_FILE=/dev/stdout ./script/cibuild

after_script:
  - bash <(curl -s https://codecov.io/bash) -cZF secure -p secure -s ./
  - bash <(curl -s https://codecov.io/bash) -cZF regular -p regular -s ./
