# Provides LWM2M_FRAMEWORK_SOURCES_DIR and LWM2M_FRAMEWORK_SOURCES variables.

set(LWM2M_FRAMEWORK_SOURCES_DIR ${CMAKE_CURRENT_LIST_DIR})
set(LWM2M_FRAMEWORK_SOURCES
    ${LWM2M_FRAMEWORK_SOURCES_DIR}/basic_lwm2m_framework.cpp
    )
