#!/bin/sh
#
# Punica - LwM2M server with REST API
# Copyright (C) 2018 8devices
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

set -e

PROJECT_ROOT_DIR="$(cd $(dirname "$0")/.. && pwd -P)"
THIRD_PARTY_DIR="${PROJECT_ROOT_DIR}/third_party"

if [ -z "${BUILD_STATIC}" ]; then
    BUILD_STATIC=true
fi

if [ -z "${BUILD_DIR}" ]; then
    BUILD_DIR="${PROJECT_ROOT_DIR}/build"
fi

if [ -z "${PREFIX_PATH_DIR}" ]; then
    PREFIX_PATH_DIR="${BUILD_DIR}"
fi

SCRIPT_NAME=$(basename -- "$0")
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

if [ -z "${LOG_FILE}" ]; then
    LOG_FILE="${PROJECT_ROOT_DIR}/${SCRIPT_NAME}_${TIMESTAMP}.log"
else
    export LOG_FILE
fi

BUILD_TOOLS_APT="git cmake build-essential autopoint autogen automake gperf bison texinfo libtool nettle-dev libtasn1-6-dev libgcrypt20-dev libunistring-dev zlib1g-dev libgmp-dev"

NETTLE_DIR="${THIRD_PARTY_DIR}/nettle"
GNUTLS_DIR="${THIRD_PARTY_DIR}/gnutls"
CURL_DIR="${THIRD_PARTY_DIR}/curl"
JANSSON_DIR="${THIRD_PARTY_DIR}/jansson"
LIBJWT_DIR="${THIRD_PARTY_DIR}/libjwt"
LIBMICROHTTPD_DIR="${THIRD_PARTY_DIR}/libmicrohttpd"
ULFFIUS_DIR="${THIRD_PARTY_DIR}/ulfius"
WAKAAMA_DIR="${THIRD_PARTY_DIR}/wakaama"

AUTORECONF_ARGS_BASE="--prepend-include=${PREFIX_PATH_DIR} -i"
CONFIGURE_ARGS_BASE="--enable-silent-rules --disable-dependency-tracking --prefix ${PREFIX_PATH_DIR}"
CMAKE_ARGS_BASE="-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX_PATH_DIR} -DCMAKE_PREFIX_PATH=${PREFIX_PATH_DIR}"
MAKE_ARGS_BASE="--quiet"

if [ "${BUILD_STATIC}" = true ]; then
    CONFIGURE_ARGS_BASE="${CONFIGURE_ARGS_BASE} --enable-static=yes --enable-shared=no"
else
    CONFIGURE_ARGS_BASE="${CONFIGURE_ARGS_BASE} --enable-shared=yes --enable-static=yes"
fi

echo_stderr () {
    echo "$@" >&2
}

library_error () {
    echo_stderr "Failed to install $1!"
    echo_stderr ""
    echo_stderr "For more information refer to \"${LOG_FILE}\""

    exit 1
}

update_repositories () {
    if which apt-get; then
        sudo apt-get update -qq
    elif which rpm; then
        echo_stderr "RPM is not supported yet!"
        return 1
    elif which opkg; then
        echo_stderr "OPKG is not supported yet!"
        return 1
    elif which brew; then
        echo_stderr "BREW is not supported yet!"
        return 1
    else
        echo_stderr "Unknown package manager! (not supported yet)"
        return 1
    fi

    return 0
}

update_submodules () {
    eval "cd ${PROJECT_ROOT_DIR}"

    git submodule update --init --recursive --quiet ||
    (
        echo_stderr "Failed to update submodules!"
        return 1
    )

    cd -
}

install_submodules () {
    install_jansson
    install_nettle
    install_gnutls
    install_libjwt
    install_libmicrohttpd
    install_curl
    install_ulfius
    install_wakaama
}

install_build_tools () {
    if which apt-get; then
        eval "sudo apt-get install -yqq ${BUILD_TOOLS_APT}"
    elif which rpm; then
        echo_stderr "RPM is not supported yet!"
        return 1
    elif which opkg; then
        echo_stderr "OPKG is not supported yet!"
        return 1
    elif which brew; then
        echo_stderr "BREW is not supported yet!"
        return 1
    else
        echo_stderr "Unknown package manager! (not supported yet)"
        return 1
    fi

    return $?
}

install_wakaama () {
    echo "    - Installing Wakaama..."

    {
        eval "${WAKAAMA_DIR}/script/setup ${CMAKE_ARGS_BASE}" &&
        eval "cd ${WAKAAMA_DIR}/build" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "Wakaama"
        return 1
    }
}

install_libjwt () {
    configure_args="${CONFIGURE_ARGS_BASE} --disable-doxygen-doc --without-openssl"

    echo "    - Installing JWT..."

    eval "cd ${LIBJWT_DIR}"

    {
        eval "autoreconf ${AUTORECONF_ARGS_BASE}" &&
        eval "./configure ${configure_args}" &&
        eval "make clean ${MAKE_ARGS_BASE}" &&
        eval "make all ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "JWT"
        return 1
    }
}

install_jansson () {
    cmake_args="${CMAKE_ARGS_BASE} -DJANSSON_WITHOUT_TESTS=on -DJANSSON_BUILD_DOCS=off -DJANSSON_EXAMPLES=off -DJANSSON_BUILD_MAN=off"
    if [ ! "${BUILD_STATIC}" = true ]; then
        cmake_args="${cmake_args} -DJANSSON_BUILD_SHARED_LIBS=1"
    fi

    echo "    - Installing Jansson..."

    eval "rm -rf ${JANSSON_DIR}/build"
    eval "mkdir ${JANSSON_DIR}/build"
    eval "cd ${JANSSON_DIR}/build"

    {
        eval "cmake ../ ${cmake_args}" &&
        eval "make ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "Jansson"
        return 1
    }
}

install_curl () {
    configure_args="${CONFIGURE_ARGS_BASE} --without-ssl --with-gnutls  --disable-ares --disable-manual --disable-proxy --disable-verbose --disable-versioned-symbols --enable-hidden-symbols --without-libidn2 --without-librtmp --disable-ldap"

    echo "    - Installing Curl..."

    eval "cd ${CURL_DIR}"

    {
        eval "${CURL_DIR}/buildconf" &&
        eval "./configure ${configure_args}" &&
        eval "make clean ${MAKE_ARGS_BASE}" &&
        eval "make ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "Curl"
        return 1
    }
}

install_nettle () {
    configure_args="${CONFIGURE_ARGS_BASE} --disable-documentation"

    echo "    - Installing Nettle..."

    eval "cd ${NETTLE_DIR}"

    {
        eval "./.bootstrap" &&
        eval "./configure ${configure_args}" &&
        eval "make clean ${MAKE_ARGS_BASE}" &&
        eval "make ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "Nettle"
        return 1
    }
}

install_gnutls () {
    configure_args="${CONFIGURE_ARGS_BASE} --disable-tests --disable-doc --without-p11-kit --without-idn --without-tpm --disable-libdane --disable-nls --disable-openssl-compatibility --disable-guile"

    echo "    - Installing GnuTLS..."

    eval "cd ${GNUTLS_DIR}"

    {
        eval "./bootstrap" &&
        eval "./configure ${configure_args}" &&
        eval "make clean ${MAKE_ARGS_BASE}" &&
        eval "make ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "GnuTLS"
        return 1
    }
}

install_libmicrohttpd () {
    configure_args="${CONFIGURE_ARGS_BASE} --enable-shared=yes --disable-curl --with-gnutls=yes"

    echo "    - Installing libmicrohttpd..."

    eval "cd ${LIBMICROHTTPD_DIR}"

    {
        eval "autoreconf ${AUTORECONF_ARGS_BASE}" &&
        eval "./configure ${configure_args}" &&
        eval "make clean ${MAKE_ARGS_BASE}" &&
        eval "make ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "libmicrohttpd"
        return 1
    }
}

install_ulfius () {
    cmake_args="${CMAKE_ARGS_BASE} -DWITH_YDER=off -DBUILD_UWSC=off  -DWITH_WEBSOCKET=off -DWITH_CURL=on"
    if [ "${BUILD_STATIC}" = true ]; then
        cmake_args="${cmake_args} -DBUILD_STATIC=on"
    fi

    echo "    - Installing Ulfius..."

    eval "rm -rf ${ULFFIUS_DIR}/build"
    eval "mkdir ${ULFFIUS_DIR}/build"
    eval "cd ${ULFFIUS_DIR}/build"

    {
        eval "cmake ../ ${cmake_args}" &&
        eval "make ${MAKE_ARGS_BASE}" &&
        eval "make clean ${MAKE_ARGS_BASE}" &&
        eval "make install ${MAKE_ARGS_BASE}" &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        library_error "Ulfius"
        return 1
    }
}

sudo -v

eval "rm -rf ${BUILD_DIR}"
eval "mkdir ${BUILD_DIR}"

echo "==> Updating package lists..."
update_repositories >> ${LOG_FILE}

echo "==> Installing building tools..."
install_build_tools >> ${LOG_FILE}

echo "==> Updating submodules..."
update_submodules >> ${LOG_FILE}

echo "==> Installing submodules..."
install_submodules

echo "Finished bootstrapping!"
