#!/bin/bash
#
# Punica - LwM2M server with REST API
# Copyright (C) 2018 8devices
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

set -e

source "$(cd $(dirname "$0") && pwd -P)/.utils"

export BUILD_DIR
eval "${SCRIPTS_DIR}/setup -DCODE_COVERAGE=ON"
eval "${SCRIPTS_DIR}/test"
###############################################################################
# FOLLOWING SECTION WAITS UNTIL COVERAGE REPORT DIRECTORIES APPEAR IN PROJECT
# DIRECTORY, BY DEFAULT TIMEOUT IS SET TO 10 s, INTERVAL IS 100 ms
# IF NO COVERAGE REPORTS APPEAR IN DIRECTORY, SCRIPT EXITS WITH CODE 1
###############################################################################
sleep_interval=0.1
sleep_timeout=10 # Timeout in seconds
for time_slept in $(seq 0.0 ${sleep_interval} ${sleep_timeout})
do
    if [ -d "regular" ] && [ -d "secure" ]; then
        eval "echo_and_log 'Time until coverage directories appeared: ${time_slept} s' >> ${LOG_FILE}"
        # If another way of making sure that coverage reports appears is found,
        # following code can be moved out of this for-if section
        eval "cp -r ${BUILD_DIR} ${PROJECT_ROOT_DIR}/src ${PROJECT_ROOT_DIR}/secure"
        eval "cp -r ${BUILD_DIR} ${PROJECT_ROOT_DIR}/src ${PROJECT_ROOT_DIR}/regular"
        eval "cp -r ${BUILD_DIR} ${PROJECT_ROOT_DIR}/src ${PROJECT_ROOT_DIR}/plugins"

        echo_and_log "Finished continuous integration procedure!"

        exit 0
    fi
    eval "sleep ${sleep_interval}"
done

echo_stderr "Not all code coverage report directories appeared in ${sleep_timeout} seconds!"
exit 1
