#!/bin/sh
#
# Punica - LwM2M server with REST API
# Copyright (C) 2018 8devices
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

set -e

PROJECT_ROOT_DIR="$(cd $(dirname "$0")/.. && pwd -P)"
SCRIPTS_DIR="${PROJECT_ROOT_DIR}/script"

SCRIPT_NAME=$(basename -- "$0")
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
LOG_FILE="${PROJECT_ROOT_DIR}/${SCRIPT_NAME}_${TIMESTAMP}.log"

CMAKE_ARGS_BASE="-DCMAKE_INSTALL_PREFIX:PATH=${PROJECT_ROOT_DIR}"

build_punica () {
    if ! [ -z "$1" ]; then
        cmake_arguments="${CMAKE_ARGS_BASE} $1"
    fi

    rm -rf ${PROJECT_ROOT_DIR}/build &&
    mkdir -p ${PROJECT_ROOT_DIR}/build/src &&
    eval "cd ${PROJECT_ROOT_DIR}/build" &&

    {
        eval "cmake ${cmake_arguments} ${PROJECT_ROOT_DIR}" &&
        make &&
        cd -
    } >> ${LOG_FILE} 2>&1 || {
        (>&2 echo "Failed to build punica!")
        (>&2 echo "\nFor more information refer to ${LOG_FILE}")

        return 1
    }
}

eval "${SCRIPTS_DIR}/bootstrap"

echo "==> Building punica..."
build_punica "$@"

echo "Finished setting up punica!"
