#!/bin/sh
#
# Punica - LwM2M server with REST API
# Copyright (C) 2018 8devices
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

set -e

PROJECT_ROOT_DIR="$(cd $(dirname "$0")/.. && pwd -P)"
SCRIPTS_DIR="${PROJECT_ROOT_DIR}/script"

TEST_PRIVATE_KEY="${PROJECT_ROOT_DIR}/private.key"
TEST_CERTIFICATE="${PROJECT_ROOT_DIR}/certificate.pem"
OTHER_TEST_PRIVATE_KEY="${PROJECT_ROOT_DIR}/other_private.key"
OTHER_TEST_CERTIFICATE="${PROJECT_ROOT_DIR}/other_certificate.pem"

generate_key_and_certificate () {
    if [ "$#" -ne 2 ]; then
        echo "Illegal number of parameters"
        return 1
    fi

    if [ -z "$1" ]; then
        echo "Private key file name argument is missing or is invalid"
        return 1
    fi
    
    if [ -z "$2" ]; then
        echo "Certificate file name argument is missing or is invalid"
        return 1
    fi

    openssl genrsa -out $1 2048

    openssl req -days 365 -out $2 -new -x509 -key $1 -subj '/CN=localhost'

    return 0
}

get_path_level() {
    ROOT_DIR="$(cd / && pwd -P)"
    level=0

    if ! [ -d "$1" ]; then
        full_path="$(cd $(dirname "$1") && pwd -P)"
    else
        full_path="$(cd "$1" && pwd -P)"
    fi
    current_path=${full_path}

    while [ "${current_path}" != "${ROOT_DIR}" ]; do
        level=$(( ${level} + 1 ));
        current_path="$(dirname ${current_path})"
    done

    echo "${level}"
}

run_punica () {
    initial_punica_arguments=""
    punica_command="${PROJECT_ROOT_DIR}/build/punica ${initial_punica_arguments}"

    if ! [ -z "$1" ]; then
        strip_level="$(get_path_level ${PROJECT_ROOT_DIR})"
        coverage_prefix="GCOV_PREFIX_STRIP=${strip_level} GCOV_PREFIX=$1"
        punica_command="${coverage_prefix} ${punica_command}"
    fi

    if ! [ -z "$2" ]; then
        punica_arguments="$2"
        punica_command="${punica_command} ${punica_arguments}"
    fi

    eval "${punica_command} > /dev/null &"

    echo $!
}

stop_punica () {
    eval "kill -2 $1"
    wait $1 || true
}

eval "${SCRIPTS_DIR}/format_style.sh --dry-run"

if [ ! -x "${PROJECT_ROOT_DIR}/build/punica" ]
then
    echo "Punica binary not found! Exiting..."
    exit 1
fi

echo "==> Generating security files..."
generate_key_and_certificate ${TEST_PRIVATE_KEY} ${TEST_CERTIFICATE}
generate_key_and_certificate ${OTHER_TEST_PRIVATE_KEY} ${OTHER_TEST_CERTIFICATE}

eval "cp ${PROJECT_ROOT_DIR}/tests/rest/database.json ${PROJECT_ROOT_DIR}/tests/rest/_database.json"

echo "==> Starting punica(-s)..."
REGULAR_PUNICA_PID=$(run_punica "regular" "-d ${PROJECT_ROOT_DIR}/tests/rest/_database.json")
SECURE_PUNICA_PID=$(run_punica "secure" "-c ${PROJECT_ROOT_DIR}/tests/rest/secure.cfg")

echo "==> Running coverage tests..."
if eval "cd ${PROJECT_ROOT_DIR}/tests/rest" && npm install && npm test
then
    coverage_tests_status=0
else
    coverage_tests_status=1
fi
cd -

echo "==> Stopping punica(-s)..."
stop_punica $REGULAR_PUNICA_PID
stop_punica $SECURE_PUNICA_PID
eval "rm -f ${PROJECT_ROOT_DIR}/tests/rest/_database.json"

exit $coverage_tests_status
